version: "3"

services:
  sonarqube:
    image: sonarqube:8.4-community
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  sonarqube_extensions:
